const axios = require('axios');
const dotenv = require('dotenv');
dotenv.config();

const DEFAULT_MODEL = process.env.GEMINI_MODEL || 'gemini-2.5-flash';
const CANDIDATE_MODELS = [
  DEFAULT_MODEL,
  'gemini-2.5-flash',
  'gemini-2.0-flash',
  'gemini-1.5-flash'
];
// Remove duplicates while preserving order
const MODEL_LIST = [...new Set(CANDIDATE_MODELS)];

const CSIT_SYSTEM_INSTRUCTION = `You are "The CSIT Vault AI Assistant", an educational and technical AI guide built for "The CSIT Vault" platform (created by Nishan Dhakal).
Your primary role is to assist students pursuing BSc. CSIT (Bachelor of Science in Computer Science and Information Technology) and computer science learners.
You help students with:
- BSc. CSIT curriculum subjects (TU / Tribhuvan University and general CS courses)
- Programming languages (C, C++, Java, Python, JavaScript, Web Tech)
- Core CS topics: Data Structures & Algorithms (DSA), Operating Systems, DBMS, Computer Networks, AI, Theory of Computation, Computer Graphics, Software Engineering, etc.
- Practical lab assignments, code solutions, debugging, and project ideas
- Exam preparation, syllabus breakdown, and concept explanations

Guidelines:
- Give clear, structured, and easy-to-understand explanations.
- Use Markdown formatting (headings, bullet points, bold text, code blocks with language tags) to make responses readable.
- Be polite, encouraging, and academically helpful.
- If asked about yourself or the platform, mention that you are the official AI Assistant for The CSIT Vault, dedicated to helping CSIT students succeed.`;

/**
 * Call Gemini API with automatic model fallback and clear error reporting.
 * @param {string} prompt - The user prompt
 * @param {Array} history - Optional previous messages [{ role: 'user'|'model', text: string }]
 * @returns {Promise<string>} - The AI response text
 */
const getGeminiResponse = async (prompt, history = []) => {
  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey || apiKey.trim() === '' || apiKey.includes('your_actual') || apiKey.includes('your_gemini')) {
    throw new Error(
      'Gemini API key is not configured. Please set a valid GEMINI_API_KEY in your .env file. Get one free at: https://aistudio.google.com/app/apikey'
    );
  }

  // Build conversation contents
  const contents = [];

  // Add historical context if provided (up to last 10 messages)
  if (Array.isArray(history) && history.length > 0) {
    const recentHistory = history.slice(-10);
    for (const msg of recentHistory) {
      if (msg.text && (msg.role === 'user' || msg.role === 'model')) {
        contents.push({
          role: msg.role,
          parts: [{ text: msg.text }]
        });
      }
    }
  }

  // Append the current user prompt
  contents.push({
    role: 'user',
    parts: [{ text: prompt }]
  });

  const requestBody = {
    contents,
    systemInstruction: {
      parts: [{ text: CSIT_SYSTEM_INSTRUCTION }]
    },
    generationConfig: {
      temperature: 0.7,
      topK: 40,
      topP: 0.95,
      maxOutputTokens: 2048
    }
  };

  let lastError = null;

  for (const model of MODEL_LIST) {
    try {
      const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
      const response = await axios.post(url, requestBody, {
        headers: { 'Content-Type': 'application/json' },
        timeout: 30000 // 30-second timeout
      });

      const replyText = response.data?.candidates?.[0]?.content?.parts?.[0]?.text;
      if (replyText) {
        return replyText;
      }
      return 'No response was generated by the AI model. Please try rephrasing your question.';
    } catch (error) {
      lastError = error;

      // If model not found or deprecated, try the next model
      if ((error.response?.status === 404 || error.response?.status === 400) && model !== MODEL_LIST[MODEL_LIST.length - 1]) {
        console.warn(`Model ${model} returned ${error.response?.status}. Trying next available model...`);
        continue;
      }

      // Format human-friendly error messages
      if (error.response) {
        const errorData = error.response.data?.error || {};
        const message = errorData.message || error.response.statusText;
        const code = error.response.status;

        console.error(`Gemini API error [${code}]:`, message);

        if (code === 403) {
          if (message.includes('leaked')) {
            throw new Error(
              'Your Gemini API key was reported as leaked and revoked by Google. Please generate a fresh API key at https://aistudio.google.com/app/apikey and update your .env file.'
            );
          }
          throw new Error(`API key permission denied or invalid: ${message}`);
        }

        if (code === 429) {
          throw new Error('Gemini API rate limit or quota exceeded. Please wait a few moments and try again.');
        }

        if (code === 404) {
          throw new Error(`Gemini model "${model}" not found for API version v1beta: ${message}`);
        }

        throw new Error(`Gemini AI Service error (${code}): ${message}`);
      } else if (error.code === 'ECONNABORTED') {
        throw new Error('Request to Gemini API timed out after 30 seconds. Please try again.');
      } else {
        throw new Error(`Network error connecting to Gemini API: ${error.message}`);
      }
    }
  }

  throw lastError || new Error('Failed to communicate with Gemini API');
};

module.exports = {
  getGeminiResponse,
  DEFAULT_MODEL,
  MODEL_LIST
};
